name: Keep Alive

on:
  schedule:
    - cron: '0 2 * * *'  # ogni giorno alle 02:00 UTC

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2
